apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: eg
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
---
apiVersion: v1
kind: Secret
metadata:
  name: gateway-cert
  namespace: envoy-gateway-system
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR0RENDQXB5Z0F3SUJBZ0lFQ1hnMU1EQU5CZ2txaGtpRzl3MEJBUXNGQURBck1SWXdGQVlEVlFRREV3MWwKYm5admVTMW5ZWFJsZDJGNU1SRXdEd1lEVlFRRkV3ZzJNRE16TlRBME56QWVGdzB5TlRBek1qWXdPRFF6TXpOYQpGdzB6TURBek1qWXdPRFF6TXpKYU1CZ3hGakFVQmdOVkJBTVREV1Z1ZG05NUxXZGhkR1YzWVhrd2dnRWlNQTBHCkNTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFEUlRwVXdjOFFRek9lS3ZFWC9UeVpncER4YTRYUmQKdTJQRFoyT0x5bE9pM0dUM3VUdDFDWjRZSDlJTS9YL01CTkVKS1MvUTAwSXpSSWc1MmVnUmtYNGxVTmszMVZabgpaVkVsZjU0eWRTdi94d3lkVkV5bXd3OHpvSnNBckxsblg3MnJ6REQrek1iMXdiTk1MbFJiUXE4MEFzRHI1blNGCjNBZU8wNENZaFJFNTNNV1JXUGFSdlFtWElUWHhoR2lvbm5xVVlScWdZWUtQanB3ZWp1a3hPOEhvVkFYM3VQV2cKaXVES1dRLzd5NmJpcXdrUUxxMWw2WFFJMmZsWTg4cGNhU2VDQjlnSG80WWcwQ3I4SkRvdDBoT1Y1VmRqeFJ4TwpGU3VYb1dZRjBDVXR2dFB5b29WRDVPeEF5bUlqZTB3QUFIUHVweEt4dVZ6MFB2b1loNncxUkIvUkFnTUJBQUdqCmdmSXdnZTh3RGdZRFZSMFBBUUgvQkFRREFnVHdNQjBHQTFVZERnUVdCQlJSdGNVcHlXa2xXT3NOVEhab3J3WjEKdEhUeVdEQWZCZ05WSFNNRUdEQVdnQlMycHU0blhpYjJndEsyVWUxQnlPbUhqV011d2pDQm5BWURWUjBSQklHVQpNSUdSZ2cxbGJuWnZlUzFuWVhSbGQyRjVnaUpsYm5admVTMW5ZWFJsZDJGNUxtVnVkbTk1TFdkaGRHVjNZWGt0CmMzbHpkR1Z0Z2labGJuWnZlUzFuWVhSbGQyRjVMbVZ1ZG05NUxXZGhkR1YzWVhrdGMzbHpkR1Z0TG5OMlk0STAKWlc1MmIza3RaMkYwWlhkaGVTNWxiblp2ZVMxbllYUmxkMkY1TFhONWMzUmxiUzV6ZG1NdVkyeDFjM1JsY2k1cwpiMk5oYkRBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQXVMUy93TWdGN1hyWXVHWnNHbXdUM3J5cTc2cXBrOGtrClV5TUJSckNjeXJVYkJMaTFZd1FXM0FSN2UyNHl6cG1XcTRNUnhST3JmaUM3QlN1N2ZyV2VOck55alJER1VKZjgKa2Jpb0FWRjBVUGJMeUt2ZmhvNTNPZU5BWURsQXRJUXV3K0IxWTF1aWdJdUgxTXF4ZHhXeVlXVnltalJ6bmYreAprWkJmb0RuS3ViNEhRemxOTGlKbXVRd3J1VDJsakgzaHNuU01FNGtKUGsrVmpJMHErcXFKR3BKcjl2VGhnU1NyCkg0QUNmekp6ak9UM2t2WFA2ekx0QitIVUVjanpJbGMxcExncDRzbHNaZHlCTHlXK3pDMCs1d3E2Nm53Vng0KzUKbyt3clBneERycGxZN2hkaXVEOVg3TncyOGxvaWVCdzloS1dGeGI5VitZWVNTYW9uU3Q1b3N3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBMFU2Vk1IUEVFTXpuaXJ4Ri8wOG1ZS1E4V3VGMFhidGp3MmRqaThwVG90eGs5N2s3CmRRbWVHQi9TRFAxL3pBVFJDU2t2ME5OQ00wU0lPZG5vRVpGK0pWRFpOOVZXWjJWUkpYK2VNblVyLzhjTW5WUk0KcHNNUE02Q2JBS3k1WjErOXE4d3cvc3pHOWNHelRDNVVXMEt2TkFMQTYrWjBoZHdIanRPQW1JVVJPZHpGa1ZqMgprYjBKbHlFMThZUm9xSjU2bEdFYW9HR0NqNDZjSG83cE1UdkI2RlFGOTdqMW9Jcmd5bGtQKzh1bTRxc0pFQzZ0ClplbDBDTm41V1BQS1hHa25nZ2ZZQjZPR0lOQXEvQ1E2TGRJVGxlVlhZOFVjVGhVcmw2Rm1CZEFsTGI3VDhxS0YKUStUc1FNcGlJM3RNQUFCejdxY1NzYmxjOUQ3NkdJZXNOVVFmMFFJREFRQUJBb0lCQVFDdkIxdlN6THdrb0hUdgptMG1kbW42cFNpMytnWkpoMzVZcGpZZTlHbENlWEZkQ29PK0xpNk5jNFI4eUpicDh6WHBRZ3RTdGVEeGZ5dXR3CkZUenZsQTg4L1VMb1ljcURaRUpiYlVESlNScW1KYm55eHMvaWxETmVKT3Y1d0hhNmIyR1pESVBjVHpvQndSMUMKazJ1UGRWQTEyaWVpSFhGTGp4Znk1QU1oaUFWRHNFcFAyeUZIWE5URWVVcm9KOHFCR3o3NUJmeVlkNzZDc0l5dQpUdGdKcDFzOUM1OHlETkRic1UxcnhQU3o2b1FTUlhsSkdZbmlSblBsYnJaY2ladjRYY2JZTGJVb0cyMkZLTG9qCmRWZkFJM0FyV3VDZERXditQekJEZDR2RUNkelE5c21TOWcyZ21LdW9JWHRRMGlXSXFOMnRvK0Z1SFoydHNRcWsKSmt2Uk5xN0JBb0dCQU5XUmhKNzZ3QlRWK25aSFhMclJTaE1YUXlnWEJ1QlRUNGtBK0VENFpadEYzZmZSZWJBVQpueDVGOXhqQ3RyZjg3VUtnVUZaU2RLcENSYjd6MXJFcnZ5T2tORUdUY1J5Q2RVY2VzSy9nd0tuVk1zREtHdzhTCjdKS241eGN4K0MzRTNXblB3d0tVaWNFTFBycE5BK0M2VkFvWHBJZU40eGNSTVZFdWZ0RlMySVROQW9HQkFQcmsKVVpsNnRVeWtQSVR6U3hNRDFDSUpSRlpJZGRNb3pNaHJVY0ZqV09KU08rMERkTUNvZXRlelhSL0lsWjJBdmpBegpEaHBvVFZwcVB0SXN3ckw1cGVPemJaNWk3ZkdvM1ROeFRtclVOLzdtY2Y3RXBmNEJLallVNUlVNGh6bS9BQjdZCjNVMk5RNjVNT1RpVDhSN2dMM0JVbWdaNEJDNnp6amsyQ2pOU1hpY1ZBb0dBR3JwdGlLQUZMaFpobEMvMk1RTkUKYkFNN1NtY25XeWZTQ21sdXFHTHVCSExJQnQzV2h1enR4UklvakpiQjIyRHlLS1o3cDNJR1c5Q1RmZ1J5V0JZTApnK0JuRWRYc0VBOWJzaHpySy9mSzVQWmp0YkVWbGR0ZWREUkRQYW5wVDRFVjNNbzlzN0wzVW91ZnZCMHJZUkt3CnRkcWpvcnRsTWx2YWVqaUJjcDBWci9rQ2dZRUFvdlFFWTlFbFRDQW9CcG9XbXNVVDFQOTcyU2E3RUdraGlOTGIKaU9YRDUwdE9ETVQvNGRvTDMybHFCS2k5TkUxWU9lb1BNT3Vwd2gzYnE1clM0bmZ2WFJNL0VXNWo2VitxUEMxTgpwMmtxN1c0emdDdXRQR3I1UmFNUVFjN1RWWmhPdGJwWkVuTzhEOHNHSjA4L2ZyUlJXMzQzaEJnVGIxbnRpWThsCjFPdWNwM2tDZ1lCWnhIRHF3bzdOeVFaOHMxbC9wK2Q1RjRLSE5kS2JTcm5saEtLYXdrSWczZkx2MFR0dmZSNDMKU2NycnV2MG5IKzdhUGdtRXBDdnB0cDluWUhxeENSWjdEY0FoM29JNUgrUk9pMmcwYzlmK0l4cmY4LzRnRlhqawp4ZFE2SlZ0K2svSmp6VHQ1bW9QTVZaNE1SZlkvT0J2bWJLeUFTd1E0ditiQldnYmNieVlVd1E9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: eg
  namespace: envoy-gateway-system
spec:
  gatewayClassName: eg
  listeners:
  - name: https
    port: 8443
    protocol: HTTPS
    tls:
      mode: Terminate
      certificateRefs:
      - name: gateway-cert
        kind: Secret
        namespace: envoy-gateway-system
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: backend
  namespace: envoy-gateway-system
spec:
  parentRefs:
    - name: eg
      sectionName: https
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: test-backend
          port: 8090
          weight: 1
---
apiVersion: v1
kind: Service
metadata:
  name: test-backend
  namespace: envoy-gateway-system
spec:
  ports:
    - port: 8090
      targetPort: 8090
      protocol: TCP
  selector:
    app: test-backend
